import { Aset } from './types';

export const INITIAL_BOSP_2025_ASETS: Aset[] = [
  // --- KIB B: PERALATAN, MESIN, ELEKTRONIK, KOMPUTER & MEBELER (RKAS 2025) ---
  {
    id: 'SAR-2025-0001',
    nama: 'Laptop ACER Swift Intel Core i7',
    merek: 'Acer Swift',
    spesifikasi: 'Intel Core i7, RAM 16GB, SSD 1TB, Intel Iris Xe Graphics, Backlight Keyboard, Fingerprint, Win 11 Home + OHS 2021',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha (TU)',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 7820000,
    serialNumber: 'ACR-SWIFT-i7-2025',
    kodeBarangBmd: '02.06.01.02.001',
    nomorRegisterBmd: '000301',
    nomorRegister: '000301',
    catatan: 'Pengadaan Komputer Laptop BOSP 2025 Tahap 1 (No. Urut RKAS 220)'
  },
  {
    id: 'SAR-2025-0002',
    nama: 'Printer Ink Tank All-in-One EPSON EcoTank L3210',
    merek: 'Epson',
    spesifikasi: 'EcoTank L3210 Print, Scan, Copy Heat-Free Ink Tank System',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha (TU)',
    jumlah: 3,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 2500000,
    serialNumber: 'EP-L3210-2025-01/03',
    kodeBarangBmd: '02.06.01.01.001',
    nomorRegisterBmd: '000302',
    nomorRegister: '000302',
    catatan: 'Pengadaan Printer BOSP 2025 Tahap 1 & 2 (No. Urut RKAS 222 & 223)'
  },
  {
    id: 'SAR-2025-0003',
    nama: 'LCD Proyektor Multimedia HD',
    merek: 'Epson / InFocus',
    spesifikasi: '3300-3600 ANSI Lumens, HDMI, VGA, Resolusi WXGA',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Media / Pembelajaran',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 3000000,
    serialNumber: 'PJ-2025-01/02',
    kodeBarangBmd: '02.06.01.05.001',
    nomorRegisterBmd: '000303',
    nomorRegister: '000303',
    catatan: 'Pengadaan Proyektor BOSP 2025 Tahap 2 (No. Urut RKAS 225)'
  },
  {
    id: 'SAR-2025-0004',
    nama: 'Layar Overhead / Screen Proyektor Tripod',
    merek: 'D-Light / ScreenPro',
    spesifikasi: 'Ukuran 70x70 inch Manual Tripod Stand',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Media / Pembelajaran',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 500000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.01.05.002',
    nomorRegisterBmd: '000304',
    nomorRegister: '000304',
    catatan: 'Pengadaan Layar Proyektor BOSP 2025 Tahap 2 (No. Urut RKAS 226)'
  },
  {
    id: 'SAR-2025-0005',
    nama: 'Uninterruptible Power Supply (UPS) Komputer / Server',
    merek: 'Prolink / APC',
    spesifikasi: 'Kapasitas 650VA - 1200VA AVR Back-up Power',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Laboratorium Komputer',
    jumlah: 4,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 1000000,
    serialNumber: 'UPS-2025-01-04',
    kodeBarangBmd: '02.06.01.02.005',
    nomorRegisterBmd: '000305',
    nomorRegister: '000305',
    catatan: 'Stabilisator Daya Lab Komputer BOSP 2025 Tahap 2 (No. Urut RKAS 198)'
  },
  {
    id: 'SAR-2025-0006',
    nama: 'Peralatan Sound System Audio Sekolah',
    merek: 'Yamaha / Behringer',
    spesifikasi: 'Active Speaker Portable Audio Outdoor/Indoor dengan Bluetooth/Mic Input',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Sanggar Seni / Ruang Guru',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 3000000,
    serialNumber: 'SND-2025-01',
    kodeBarangBmd: '02.06.01.04.001',
    nomorRegisterBmd: '000306',
    nomorRegister: '000306',
    catatan: 'Pengadaan Sound System BOSP 2025 Tahap 2 (No. Urut RKAS 199)'
  },
  {
    id: 'SAR-2025-0007',
    nama: 'Kamera Pengawas CCTV HD Outdoor/Indoor',
    merek: 'Hikvision / Dahua',
    spesifikasi: 'Resolusi 2MP Full HD IR Night Vision Weatherproof',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Lingkungan Sekolah / Koridor',
    jumlah: 5,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 500000,
    serialNumber: 'CCTV-2025-01-05',
    kodeBarangBmd: '02.06.01.05.010',
    nomorRegisterBmd: '000307',
    nomorRegister: '000307',
    catatan: 'Keamanan Lingkungan Sekolah BOSP 2025 Tahap 2 (No. Urut RKAS 200)'
  },
  {
    id: 'SAR-2025-0008',
    nama: 'Meja Siswa Standar Sekolah',
    merek: 'Lokal Industri Mebel',
    spesifikasi: 'Rangka Kayu Solid Halus Pelitur Tebal',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Kelas Belajar',
    jumlah: 4,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 700000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.02.01.001',
    nomorRegisterBmd: '000308',
    nomorRegister: '000308',
    catatan: 'Pengadaan Mebel Meja Siswa BOSP 2025 Tahap 2 (No. Urut RKAS 193)'
  },
  {
    id: 'SAR-2025-0009',
    nama: 'Kipas Angin Dinding Maspion Heavy Duty',
    merek: 'Maspion',
    spesifikasi: 'Industrial Wall Fan 18-20 Inch Motor Tembaga Kuat',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Kelas Belajar',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 1500000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.02.01.005',
    nomorRegisterBmd: '000309',
    nomorRegister: '000309',
    catatan: 'Kenyamanan Ruang Belajar BOSP 2025 Tahap 1 (No. Urut RKAS 195)'
  },
  {
    id: 'SAR-2025-0010',
    nama: 'Kipas Angin Stand Miyako',
    merek: 'Miyako',
    spesifikasi: 'Stand Fan 16 Inch 3 Tingkat Kecepatan Timer',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Guru',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 750000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.02.01.005',
    nomorRegisterBmd: '000310',
    nomorRegister: '000310',
    catatan: 'Fasilitas Kantor Guru BOSP 2025 Tahap 2 (No. Urut RKAS 196)'
  },
  {
    id: 'SAR-2025-0011',
    nama: 'Mesin Pemotong Rumput Gendong 4-Tak',
    merek: 'Honda / Tasco',
    spesifikasi: 'Mesin 4-Tak OHV Hemat Bensin Pisau Baja Tajam',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Gudang Sarpras',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 2500000,
    serialNumber: 'MTR-4T-2025',
    kodeBarangBmd: '02.06.03.01.001',
    nomorRegisterBmd: '000311',
    nomorRegister: '000311',
    catatan: 'Peralatan Kebersihan Lapangan BOSP 2025 Tahap 2 (No. Urut RKAS 194)'
  },
  {
    id: 'SAR-2025-0012',
    nama: 'Tangki Sprayer Elektrik Kebun / Disinfektan',
    merek: 'Swan / CBA Elektrik',
    spesifikasi: 'Kapasitas 16 Liter Baterai Rechargeable Nozzle Kuningan',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Gudang Sarpras',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 1500000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.03.01.006',
    nomorRegisterBmd: '000312',
    nomorRegister: '000312',
    catatan: 'Alat Perawatan Kebun/Sanitasi BOSP 2025 Tahap 2 (No. Urut RKAS 191)'
  },
  {
    id: 'SAR-2025-0013',
    nama: 'Timbangan Badan Digital Medis (UKS)',
    merek: 'Camry / Gea Medical',
    spesifikasi: 'Kapasitas 180 Kg Presisi Layar LCD Backlight',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang UKS',
    jumlah: 2,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 500000,
    serialNumber: 'TMB-UKS-2025-01/02',
    kodeBarangBmd: '02.06.04.01.003',
    nomorRegisterBmd: '000313',
    nomorRegister: '000313',
    catatan: 'Peralatan Medis UKS BOSP 2025 Tahap 2 (No. Urut RKAS 90)'
  },
  {
    id: 'SAR-2025-0014',
    nama: 'Tandu Lipat Emergency Aluminium (UKS)',
    merek: 'Gea / Onemed',
    spesifikasi: 'Aluminium Alloy Ringan Kuat Sabuk Pengaman Medis',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang UKS',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 3000000,
    serialNumber: 'TND-UKS-2025',
    kodeBarangBmd: '02.06.04.01.001',
    nomorRegisterBmd: '000314',
    nomorRegister: '000314',
    catatan: 'Peralatan Emergency UKS BOSP 2025 Tahap 2 (No. Urut RKAS 91)'
  },
  {
    id: 'SAR-2025-0015',
    nama: 'Matras Senam Lantai Olahraga / Kesehatan (200x100x10 cm)',
    merek: 'Olympus Sports',
    spesifikasi: 'Ukuran 200 x 100 x 10 cm Busa Rebonded Density Tinggi Cover Kulit Sintetis',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 2000000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.04.01.002',
    nomorRegisterBmd: '000315',
    nomorRegister: '000315',
    catatan: 'Peralatan Senam UKS & Olahraga BOSP 2025 Tahap 2 (No. Urut RKAS 92)'
  },
  {
    id: 'SAR-2025-0016',
    nama: 'Kompor Gas 1000 Mata Komersil Dapur Sekolah',
    merek: 'Solid / Sunrise',
    spesifikasi: 'Kompor Gas Tekanan Rendah / Tinggi Burner Cast Iron 1000 Mata',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Dapur / Ruang Guru',
    jumlah: 2,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 500000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.02.01.010',
    nomorRegisterBmd: '000316',
    nomorRegister: '000316',
    catatan: 'Perlengkapan Rumah Tangga Dapur BOSP 2025 Tahap 2 (No. Urut RKAS 285)'
  },

  // --- KIB E: ALAT OLAHRAGA TAHAN LAMA (RKAS 2025) ---
  {
    id: 'SAR-2025-0017',
    nama: 'Bola Voli Atlet Standar PBVSI',
    merek: 'Mikasa / Molten',
    spesifikasi: 'Bahan Kulit Sintetis Laminated Soft Touch',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 300000,
    kodeBarangBmd: '05.17.02.01.005',
    nomorRegisterBmd: '000317',
    nomorRegister: '000317',
    catatan: 'Peralatan Ekstrakurikuler Olahraga BOSP 2025 Tahap 1 (No. Urut RKAS 59)'
  },
  {
    id: 'SAR-2025-0018',
    nama: 'Bola Sepak / Bola Kaki Standar FIFA Size 5',
    merek: 'Specs / Mikasa',
    spesifikasi: 'PU Leather Jahit Mesin Presisi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 500000,
    kodeBarangBmd: '05.17.02.01.004',
    nomorRegisterBmd: '000318',
    nomorRegister: '000318',
    catatan: 'Peralatan Olahraga BOSP 2025 Tahap 1 (No. Urut RKAS 60)'
  },
  {
    id: 'SAR-2025-0019',
    nama: 'Bola Sepak Takraw Marathon 201',
    merek: 'Marathon 201',
    spesifikasi: 'Anyaman Sintetis Standar ISTAF / PSTI',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 200000,
    kodeBarangBmd: '05.17.02.01.003',
    nomorRegisterBmd: '000319',
    nomorRegister: '000319',
    catatan: 'Peralatan Atlet Sepak Takraw BOSP 2025 Tahap 1 (No. Urut RKAS 61)'
  },
  {
    id: 'SAR-2025-0020',
    nama: 'Bola Basket Molten Size 6',
    merek: 'Molten',
    spesifikasi: 'Ukuran Size 6 Rubber / Composite Leather Grip Nyaman',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 4,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 425000,
    kodeBarangBmd: '05.17.02.01.006',
    nomorRegisterBmd: '000320',
    nomorRegister: '000320',
    catatan: 'Peralatan Basket BOSP 2025 Tahap 1 & 2 (No. Urut RKAS 62 & 249)'
  },
  {
    id: 'SAR-2025-0021',
    nama: 'Bola Futsal Standar PSSI',
    merek: 'Specs / Molten',
    spesifikasi: 'Size 4 Low Bounce Laminated',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 130000,
    kodeBarangBmd: '05.17.02.01.007',
    nomorRegisterBmd: '000321',
    nomorRegister: '000321',
    catatan: 'Peralatan Futsal BOSP 2025 Tahap 2 (No. Urut RKAS 250)'
  },
  {
    id: 'SAR-2025-0022',
    nama: 'Setik Stik Drumband Sekolah',
    merek: 'Marching Drum Stick',
    spesifikasi: 'Kayu Maple / Hickory Padat Sepasang Kualitas Tinggi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Sanggar Seni',
    jumlah: 10,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 70000,
    kodeBarangBmd: '05.17.02.01.008',
    nomorRegisterBmd: '000322',
    nomorRegister: '000322',
    catatan: 'Peralatan Seni Musik & Drumband BOSP 2025 Tahap 2 (No. Urut RKAS 202)'
  }
];
