import { Aset } from './types';

export const INITIAL_BOSP_2026_ASETS: Aset[] = [
  // --- KIB B: PERALATAN, MESIN, ELEKTRONIK, KOMPUTER & MEBELER (RKAS 2026) ---
  {
    id: 'SAR-2026-0001',
    nama: 'Mesin Pompa Air Otomatis',
    merek: 'Shimizu / Panasonic',
    spesifikasi: 'Pompa Air Otomatis Sumur Dangkal/Dalam Suplai Sanitasi Sekolah',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Lingkungan Sekolah / Sanitasi',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 1500000,
    serialNumber: 'PMP-2026-01',
    kodeBarangBmd: '02.02.01.03.005',
    nomorRegisterBmd: '000401',
    nomorRegister: '000401',
    catatan: 'Pengadaan Mesin Pompa Air BOSP 2026 Tahap 1 (No. Urut RKAS 233)'
  },
  {
    id: 'SAR-2026-0002',
    nama: 'Lemari Etalase Aluminium (Pintu Kaca)',
    merek: 'Custom Aluminium Glass',
    spesifikasi: 'Rangka Aluminium Tebal, Rak Kaca Transparan, Kunci Pengaman',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Guru / TU',
    jumlah: 3,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 2800000,
    serialNumber: 'LMR-ALM-2026-01/03',
    kodeBarangBmd: '02.06.02.01.001',
    nomorRegisterBmd: '000402',
    nomorRegister: '000402',
    catatan: 'Pengadaan Lemari Etalase BOSP 2026 Tahap 1 (No. Urut RKAS 234)'
  },
  {
    id: 'SAR-2026-0003',
    nama: 'Kursi Kantor Staf & Guru',
    merek: 'Futura / Chitose',
    spesifikasi: 'Kursi Susun Busa Tebal Krom Anti-Karat',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Guru',
    jumlah: 25,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 200000,
    serialNumber: 'KRS-KTR-2026-01/25',
    kodeBarangBmd: '02.06.02.01.002',
    nomorRegisterBmd: '000403',
    nomorRegister: '000403',
    catatan: 'Pengadaan Kursi Kantor BOSP 2026 Tahap 1 (No. Urut RKAS 235)'
  },
  {
    id: 'SAR-2026-0004',
    nama: 'Air Conditioner (AC) 1 PK',
    merek: 'Daikin / Panasonic 1 PK',
    spesifikasi: 'Kapasitas 1 PK Low Watt Refrigerant R32 Hemat Energi',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Laboratorium Komputer',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 5500000,
    serialNumber: 'AC-1PK-2026-01',
    kodeBarangBmd: '02.06.02.01.004',
    nomorRegisterBmd: '000404',
    nomorRegister: '000404',
    catatan: 'Pengadaan AC Ruang Komputer BOSP 2026 Tahap 2 (No. Urut RKAS 236)'
  },
  {
    id: 'SAR-2026-0005',
    nama: 'Dispenser Air Minum (Galon Bawah)',
    merek: 'Miyako / Sanken',
    spesifikasi: 'Bottom Loading 3 Kran (Panas, Normal, Dingin) Safety Child Lock',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Guru',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 2500000,
    serialNumber: 'DSP-2026-01',
    kodeBarangBmd: '02.06.02.01.006',
    nomorRegisterBmd: '000405',
    nomorRegister: '000405',
    catatan: 'Pengadaan Dispenser BOSP 2026 Tahap 2 (No. Urut RKAS 237)'
  },
  {
    id: 'SAR-2026-0006',
    nama: 'Meja Biro Kerja Kayu',
    merek: 'Lokal Industri Mebel Jepara',
    spesifikasi: 'Kayu Solid Ukuran 120x60 cm dengan Laci dan Kunci',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha (TU)',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 2000000,
    serialNumber: 'MJ-BIRO-2026-01',
    kodeBarangBmd: '02.06.02.01.001',
    nomorRegisterBmd: '000406',
    nomorRegister: '000406',
    catatan: 'Pengadaan Meja Biro BOSP 2026 Tahap 2 (No. Urut RKAS 252)'
  },
  {
    id: 'SAR-2026-0007',
    nama: 'Kursi Biro Kerja Putar',
    merek: 'Indachi / Chairman',
    spesifikasi: 'Kursi Putar Hidrolik Busa Rebonded Sandaran Jaring Ergonomis',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha (TU)',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 500000,
    serialNumber: 'KR-BIRO-2026-01',
    kodeBarangBmd: '02.06.02.01.001',
    nomorRegisterBmd: '000407',
    nomorRegister: '000407',
    catatan: 'Pengadaan Kursi Biro BOSP 2026 Tahap 2 (No. Urut RKAS 253)'
  },
  {
    id: 'SAR-2026-0008',
    nama: 'Ambal / Karpet Ruang Pertemuan',
    merek: 'Permadani Modern',
    spesifikasi: 'Karpet Lantai Motif Elegan Lebar 2x30 Meter Roll',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Rapat / Aula',
    jumlah: 1,
    satuan: 'Roll',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 2000000,
    serialNumber: 'AMB-2026-01',
    kodeBarangBmd: '02.06.02.01.006',
    nomorRegisterBmd: '000408',
    nomorRegister: '000408',
    catatan: 'Pengadaan Karpet/Ambal BOSP 2026 Tahap 1 (No. Urut RKAS 254)'
  },
  {
    id: 'SAR-2026-0009',
    nama: 'Kamera CCTV Pengawas & Alat Peraga Siswa',
    merek: 'Hikvision / Dahua 2MP Full HD',
    spesifikasi: 'Kamera Pengawas IP CCTV 2MP IR Night Vision Outdoor/Indoor',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Laboratorium Komputer',
    jumlah: 5,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 500000,
    serialNumber: 'CCTV-2026-01-05',
    kodeBarangBmd: '02.06.01.05.010',
    nomorRegisterBmd: '000409',
    nomorRegister: '000409',
    catatan: 'Alat Praktek dan Peraga Siswa CCTV BOSP 2026 Tahap 1 (No. Urut RKAS 255)'
  },
  {
    id: 'SAR-2026-0010',
    nama: 'PC All-in-One ASUS AIO F5401WUA Ryzen 7',
    merek: 'ASUS AIO PC F5401WUA',
    spesifikasi: 'AMD Ryzen 7 5700U, RAM 16GB, SSD 512GB + HDD 1TB, Layar 23.8" FHD IPS, Win 10',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Laboratorium Komputer',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 20000000,
    serialNumber: 'ASUS-AIO-R7-2026',
    kodeBarangBmd: '02.06.01.02.001',
    nomorRegisterBmd: '000410',
    nomorRegister: '000410',
    catatan: 'Pengadaan PC All-in-One Pembelajaran BOSP 2026 Tahap 2 (No. Urut RKAS 269)'
  },
  {
    id: 'SAR-2026-0011',
    nama: 'Laptop Intel Core i5 RAM 8GB SSD 512GB',
    merek: 'Acer / Asus / Lenovo Intel Core i5',
    spesifikasi: 'Intel Core i5-1035G1, RAM 8GB DDR4, SSD 512GB M.2 NVMe, Layar 14" FHD',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha (TU)',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 11000000,
    serialNumber: 'LTP-i5-2026-01',
    kodeBarangBmd: '02.06.01.02.002',
    nomorRegisterBmd: '000411',
    nomorRegister: '000411',
    catatan: 'Pengadaan Laptop Pembelajaran & Administrasi BOSP 2026 Tahap 1 (No. Urut RKAS 271)'
  },
  {
    id: 'SAR-2026-0012',
    nama: 'Printer Ink Tank All-in-One EPSON EcoTank L3210 (Tahap 1)',
    merek: 'Epson EcoTank L3210',
    spesifikasi: 'EcoTank L3210 Print, Scan, Copy Heat-Free Ink Tank System Original',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha (TU)',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 2700000,
    serialNumber: 'EP-L3210-2026-01',
    kodeBarangBmd: '02.06.01.01.001',
    nomorRegisterBmd: '000412',
    nomorRegister: '000412',
    catatan: 'Pengadaan Printer L3210 BOSP 2026 Tahap 1 (No. Urut RKAS 273)'
  },
  {
    id: 'SAR-2026-0013',
    nama: 'Printer Ink Tank All-in-One EPSON EcoTank L3210 (Tahap 2)',
    merek: 'Epson EcoTank L3210',
    spesifikasi: 'EcoTank L3210 Print, Scan, Copy Heat-Free Ink Tank System Original',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Guru',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 2700000,
    serialNumber: 'EP-L3210-2026-02',
    kodeBarangBmd: '02.06.01.01.001',
    nomorRegisterBmd: '000413',
    nomorRegister: '000413',
    catatan: 'Pengadaan Printer L3210 BOSP 2026 Tahap 2 (No. Urut RKAS 273)'
  },
  {
    id: 'SAR-2026-0014',
    nama: 'LCD Projector Multimedia High Lumens (Tahap 1)',
    merek: 'Epson / InFocus 3600 Lumens',
    spesifikasi: '3600 ANSI Lumens, Port HDMI/VGA, Resolusi XGA/WXGA Pembelajaran',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Media / Pembelajaran',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 7000000,
    serialNumber: 'PJ-2026-01',
    kodeBarangBmd: '02.06.01.05.001',
    nomorRegisterBmd: '000414',
    nomorRegister: '000414',
    catatan: 'Pengadaan LCD Proyektor BOSP 2026 Tahap 1 (No. Urut RKAS 275)'
  },
  {
    id: 'SAR-2026-0015',
    nama: 'LCD Projector Multimedia High Lumens (Tahap 2)',
    merek: 'Epson / InFocus 3600 Lumens',
    spesifikasi: '3600 ANSI Lumens, Port HDMI/VGA, Resolusi XGA/WXGA Pembelajaran',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Kelas Belajar',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 7000000,
    serialNumber: 'PJ-2026-02',
    kodeBarangBmd: '02.06.01.05.001',
    nomorRegisterBmd: '000415',
    nomorRegister: '000415',
    catatan: 'Pengadaan LCD Proyektor BOSP 2026 Tahap 2 (No. Urut RKAS 275)'
  },
  {
    id: 'SAR-2026-0016',
    nama: 'Meja Tenis Meja Sport Premium',
    merek: 'Butterfly / Shiamiq Premium Standar ITTF',
    spesifikasi: 'Papan MDF Tebal 18-25mm Rangka Roda Kunci Lipat Otomatis',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Olahraga / Aula',
    jumlah: 1,
    satuan: 'Set',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 5000000,
    serialNumber: 'TM-2026-01',
    kodeBarangBmd: '02.08.03.06.011',
    nomorRegisterBmd: '000416',
    nomorRegister: '000416',
    catatan: 'Pengadaan Tenis Meja Sport BOSP 2026 Tahap 2 (No. Urut RKAS 316)'
  },
  {
    id: 'SAR-2026-0017',
    nama: 'Patung Manekin Full Body (Alat Peraga Biologi/Kesehatan)',
    merek: 'Anatomical Model Full Body',
    spesifikasi: 'Manekin Tubuh Manusia Lengkap Organ Anatomi untuk Praktikum Siswa',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Laboratorium Biologi / IPA',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 750000,
    serialNumber: 'MNK-2026-01',
    kodeBarangBmd: '02.08.03.06.016',
    nomorRegisterBmd: '000417',
    nomorRegister: '000417',
    catatan: 'Alat Praktek dan Peraga Siswa Patung Manekin BOSP 2026 Tahap 1 (No. Urut RKAS 317)'
  },
  {
    id: 'SAR-2026-0018',
    nama: 'Matras Pencak Silat Standar Pertandingan (1 Lapangan)',
    merek: 'Standar IPSI Eva Foam',
    spesifikasi: 'Matras Puzzle Eva Foam Tebal 3-5 cm Density Tinggi Ukuran 1x1 Meter',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Olahraga / Lapangan Indoor',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 2000000,
    serialNumber: 'MTR-2026-01/02',
    kodeBarangBmd: '02.19.01.06.001',
    nomorRegisterBmd: '000418',
    nomorRegister: '000418',
    catatan: 'Perlengkapan Olahraga Matras Pencak Silat BOSP 2026 Tahap 1 (No. Urut RKAS 318)'
  },

  // --- KIB E: ASET TETAP LAINNYA / BUKU PERPUSTAKAAN & KITAB (RKAS 2026) ---
  {
    id: 'ATL-2026-0001',
    nama: 'Mushaf Al-Qur\'an Al-Khobir (Tajwid & Terjemah)',
    judulBuku: 'Al-Qur\'an Al-Khobir Tajwid dan Terjemah Per Kata',
    pengarangBuku: 'Tim Lajnah Pentashihan Mushaf Al-Qur\'an',
    penerbitBuku: 'Penerbit Nur Ilmu Mandiri',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan / Musholla',
    jumlah: 5,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 130000,
    kodeBarangBmd: '05.17.01.01.003',
    nomorRegisterBmd: '000501',
    nomorRegister: '000501',
    catatan: 'Pengadaan Al-Qur\'an BOSP 2026 Tahap 1 (No. Urut RKAS 319)'
  },
  {
    id: 'ATL-2026-0002',
    nama: 'Buku Teks Siswa: PJOK Kelas X (Kurikulum Merdeka)',
    judulBuku: 'Pendidikan Jasmani, Olahraga, dan Kesehatan untuk SMA/MA/SMK/MAK Kelas X',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 33400,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000502',
    nomorRegister: '000502',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 117)'
  },
  {
    id: 'ATL-2026-0003',
    nama: 'Buku Teks Siswa: Pendidikan Pancasila Kelas X (Kurikulum Merdeka)',
    judulBuku: 'Pendidikan Pancasila untuk SMA/MA/SMK/MAK Kelas X',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 32200,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000503',
    nomorRegister: '000503',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 118)'
  },
  {
    id: 'ATL-2026-0004',
    nama: 'Buku Teks Siswa: Bahasa Inggris Work in Progress Kelas X',
    judulBuku: 'Bahasa Inggris : Work in Progress untuk SMA/SMK/MA Kelas X',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 26100,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000504',
    nomorRegister: '000504',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 119)'
  },
  {
    id: 'ATL-2026-0005',
    nama: 'Buku Teks Siswa: Informatika Kelas X (Kurikulum Merdeka)',
    judulBuku: 'Informatika untuk SMA Kelas X',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 33600,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000505',
    nomorRegister: '000505',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 120)'
  },
  {
    id: 'ATL-2026-0006',
    nama: 'Buku Teks Siswa: PAI dan Budi Pekerti Kelas X',
    judulBuku: 'Pendidikan Agama Islam dan Budi Pekerti untuk SMA/SMK Kelas X',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 42100,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000506',
    nomorRegister: '000506',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 121)'
  },
  {
    id: 'ATL-2026-0007',
    nama: 'Buku Teks Siswa: Bahasa Indonesia Cerdas Cergas Kelas X',
    judulBuku: 'Cerdas Cergas Berbahasa dan Bersastra Indonesia untuk SMA/SMK Kelas X',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 31200,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000507',
    nomorRegister: '000507',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 122)'
  },
  {
    id: 'ATL-2026-0008',
    nama: 'Buku Teks Siswa: Matematika Kelas X (Kurikulum Merdeka)',
    judulBuku: 'Matematika untuk SMA/SMK Kelas X',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 35400,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000508',
    nomorRegister: '000508',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 123)'
  },
  {
    id: 'ATL-2026-0009',
    nama: 'Buku Teks Siswa: IPA Terpadu Kelas X',
    judulBuku: 'Ilmu Pengetahuan Alam untuk SMA Kelas X',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 34800,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000509',
    nomorRegister: '000509',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 124)'
  },
  {
    id: 'ATL-2026-0010',
    nama: 'Buku Teks Siswa: IPS Terpadu Kelas X',
    judulBuku: 'Ilmu Pengetahuan Sosial untuk SMA Kelas X',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 42100,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000510',
    nomorRegister: '000510',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 125)'
  },
  {
    id: 'ATL-2026-0011',
    nama: 'Buku Teks Siswa: PJOK Kelas XI (Kurikulum Merdeka)',
    judulBuku: 'Pendidikan Jasmani, Olahraga, dan Kesehatan untuk SMA/MA/SMK/MAK Kelas XI',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 35500,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000511',
    nomorRegister: '000511',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 126)'
  },
  {
    id: 'ATL-2026-0012',
    nama: 'Buku Teks Siswa: Bahasa Indonesia Kelas XI (Edisi Revisi)',
    judulBuku: 'Cerdas Cergas Berbahasa dan Bersastra Indonesia untuk SMA/MA/SMK/MAK Kelas XI (Edisi Revisi)',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 43600,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000512',
    nomorRegister: '000512',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 127)'
  },
  {
    id: 'ATL-2026-0013',
    nama: 'Buku Teks Siswa: Matematika Tingkat Lanjut Kelas XI (Revisi)',
    judulBuku: 'Matematika Tingkat Lanjut untuk SMA/MA Kelas XI (Edisi Revisi)',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 43600,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000513',
    nomorRegister: '000513',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 128)'
  },
  {
    id: 'ATL-2026-0014',
    nama: 'Buku Teks Siswa: Sosiologi Kelas XI (Edisi Revisi)',
    judulBuku: 'Sosiologi untuk SMA/MA Kelas XI (Edisi Revisi)',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 31400,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000514',
    nomorRegister: '000514',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 129)'
  },
  {
    id: 'ATL-2026-0015',
    nama: 'Buku Teks Siswa: Geografi Kelas XI (Edisi Revisi)',
    judulBuku: 'Geografi untuk SMA/MA Kelas XI (Edisi Revisi)',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 39500,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000515',
    nomorRegister: '000515',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 130)'
  },
  {
    id: 'ATL-2026-0016',
    nama: 'Buku Teks Siswa: Ekonomi Kelas XI (Edisi Revisi)',
    judulBuku: 'Ekonomi untuk SMA/MA Kelas XI (Edisi Revisi)',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 30700,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000516',
    nomorRegister: '000516',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 1 (No. Urut RKAS 131)'
  },
  {
    id: 'ATL-2026-0017',
    nama: 'Buku Teks Siswa: Pendidikan Pancasila Kelas XII',
    judulBuku: 'Pendidikan Pancasila untuk SMA/MA/SMK/MAK Kelas XII',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 32200,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000517',
    nomorRegister: '000517',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 2 (No. Urut RKAS 138)'
  },
  {
    id: 'ATL-2026-0018',
    nama: 'Buku Teks Siswa: Matematika Kelas XII',
    judulBuku: 'Matematika untuk SMA/SMK/MA Kelas XII',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 24200,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000518',
    nomorRegister: '000518',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 2 (No. Urut RKAS 139)'
  },
  {
    id: 'ATL-2026-0019',
    nama: 'Buku Teks Siswa: Sejarah Kelas XII',
    judulBuku: 'Sejarah untuk SMA/MA Kelas XII',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 32200,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000519',
    nomorRegister: '000519',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 2 (No. Urut RKAS 141)'
  },
  {
    id: 'ATL-2026-0020',
    nama: 'Buku Teks Siswa: Biologi Kelas XII',
    judulBuku: 'Biologi untuk SMA/MA Kelas XII',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 33500,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000520',
    nomorRegister: '000520',
    catatan: 'Pengadaan Buku Teks Siswa BOSP 2026 Tahap 2 (No. Urut RKAS 142)'
  }
];
