import { Aset } from './types';

export const INITIAL_BOSP_2023_ASETS: Aset[] = [
  // --- KIB B: PERALATAN, MESIN & TIK (BELANJA MODAL RKAS 2023) ---
  {
    id: 'SAR-2023-0001',
    nama: 'Uninterruptible Power Supply (UPS) Lab Komputer',
    merek: 'ICA / Prolink / APC',
    spesifikasi: 'UPS 1200VA / 2000VA Backup Power Stabilizer Lab',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Laboratorium Komputer',
    jumlah: 4,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 2000000,
    serialNumber: 'UPS-2023-001/004',
    kodeBarangBmd: '02.06.01.05.006',
    nomorRegisterBmd: '000001',
    nomorRegister: '000001',
    catatan: 'Pengadaan Sarana Lab Komputer Tahap 1 (No. Urut RKAS 16 - Rekening 5.2.02.10.02.0005)'
  },
  {
    id: 'SAR-2023-0002',
    nama: 'LAN Tester Jaringan Komputer',
    merek: 'Kyoritsu / Networx',
    spesifikasi: 'RJ45 RJ11 Cable Tester Checker Lab',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Laboratorium Komputer',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 170000,
    serialNumber: 'LT-2023-001',
    kodeBarangBmd: '02.06.01.05.007',
    nomorRegisterBmd: '000002',
    nomorRegister: '000002',
    catatan: 'Alat Pengujian Jaringan Komputer Tahap 1 (No. Urut RKAS 17 - Rekening 5.2.02.10.02.0005)'
  },
  {
    id: 'SAR-2023-0003',
    nama: 'Switch Hub / Switch Backer Jaringan LAN',
    merek: 'TP-Link / D-Link 24-Port Gigabit',
    spesifikasi: 'Switch Network Rackmount Managed/Unmanaged Gigabit',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Server / Lab Komputer',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 1500000,
    serialNumber: 'SW-2023-001',
    kodeBarangBmd: '02.06.01.05.008',
    nomorRegisterBmd: '000003',
    nomorRegister: '000003',
    catatan: 'Bahan Praktik Jaringan Komputer Tahap 2 (No. Urut RKAS 19 - Rekening 5.2.02.10.01.0001)'
  },
  {
    id: 'SAR-2023-0004',
    nama: 'Antena MF/MW Portable Komunikasi',
    merek: 'Diamond / Telex',
    spesifikasi: 'Antena Portable MF/MW Receiver/Transceiver Radio Sekolah',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Multimedia / OSIS',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 961000,
    serialNumber: 'ANT-2023-001',
    kodeBarangBmd: '02.06.02.01.001',
    nomorRegisterBmd: '000004',
    nomorRegister: '000004',
    catatan: 'Peralatan Antena Radio/Komunikasi Tahap 2 (No. Urut RKAS 20 - Rekening 5.2.02.10.01.0001)'
  },
  {
    id: 'SAR-2023-0005',
    nama: 'Kipas Angin Dinding / Stand Ruang Belajar',
    merek: 'Maspion / Cosmos 16-18 Inch',
    spesifikasi: 'Kipas Angin Heavy Duty Wall/Stand Fan Ruang Kelas',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Kelas / TU',
    jumlah: 4,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 1500000,
    serialNumber: 'FAN-2023-001/004',
    kodeBarangBmd: '02.06.01.02.001',
    nomorRegisterBmd: '000005',
    nomorRegister: '000005',
    catatan: 'Sarana Penunjang Ruang Belajar & Guru (No. Urut RKAS 48 - Rekening 5.2.02.05.02.0004)'
  },
  {
    id: 'SAR-2023-0006',
    nama: 'Modem Router Jaringan Internet Sekolah',
    merek: 'Huawei / ZTE / TP-Link Wireless Router',
    spesifikasi: 'Gigabit Dual Band High-Gain Modem Router Internet',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Server / TU',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 2550000,
    serialNumber: 'MDM-2023-001',
    kodeBarangBmd: '02.06.01.05.009',
    nomorRegisterBmd: '000006',
    nomorRegister: '000006',
    catatan: 'Pemasangan Jaringan Internet Baru Tahap 1 (No. Urut RKAS 51 - Rekening 5.2.02.10.02.0004)'
  },
  {
    id: 'SAR-2023-0007',
    nama: 'Mesin Pompa Air Otomatis',
    merek: 'Shimizu / Panasonic Jet Pump',
    spesifikasi: 'Pompa Air Sumur Dangkal/Dalam Otomatis Sanitasi Sekolah',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Pompa Air / Sanitasi',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 800000,
    serialNumber: 'PMP-2023-001',
    kodeBarangBmd: '02.03.01.03.001',
    nomorRegisterBmd: '000007',
    nomorRegister: '000007',
    catatan: 'Instalasi Air & Sanitasi Sekolah Tahap 2 (No. Urut RKAS 54 - Rekening 5.2.02.01.03.0005)'
  },
  {
    id: 'SAR-2023-0008',
    nama: 'Mesin Pemotong Rumput Lapangan / Taman',
    merek: 'Honda / Tanika 2 Tak / 4 Tak',
    spesifikasi: 'Mesin Potong Rumput Gendong Pemeliharaan Lapangan & Taman',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Gudang Sarpras & Kebersihan',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 2500000,
    serialNumber: 'MPR-2023-001',
    kodeBarangBmd: '02.06.01.02.002',
    nomorRegisterBmd: '000008',
    nomorRegister: '000008',
    catatan: 'Pemeliharaan Taman & Lapangan Tahap 2 (No. Urut RKAS 85 - Rekening 5.2.02.05.02.0003)'
  },
  {
    id: 'SAR-2023-0009',
    nama: 'Microphone / Wireless Mic Sound System Sekolah',
    merek: 'Shure / Sennheiser Wireless Double Mic',
    spesifikasi: 'Dual Wireless Handheld Microphone Receiver UHF',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Guru / Sound System Upacara',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 5000000,
    serialNumber: 'MIC-2023-001',
    kodeBarangBmd: '02.06.02.01.002',
    nomorRegisterBmd: '000009',
    nomorRegister: '000009',
    catatan: 'Pengadaan Peralatan Kantor & Upacara Tahap 2 (No. Urut RKAS 87 - Rekening 5.2.02.05.01.0005)'
  },
  {
    id: 'SAR-2023-0010',
    nama: 'LCD Proyektor Multimedia Pembelajaran',
    merek: 'Epson / InFocus 3600 Lumens',
    spesifikasi: 'Resolusi XGA/WXGA, HDMI/VGA/USB, Long Lamp Life',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Media / Kelas Pembelajaran',
    jumlah: 3,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 5000000,
    serialNumber: 'PJ-2023-001/003',
    kodeBarangBmd: '02.06.01.05.001',
    nomorRegisterBmd: '000010',
    nomorRegister: '000010',
    catatan: 'Pengadaan Multimedia Pembelajaran Tahap 1 & 2 (No. Urut RKAS 90 - Rekening 5.2.05.01.02.0001)'
  },
  {
    id: 'SAR-2023-0011',
    nama: 'Layar Overhead / Screen Proyektor Tripod Kelas',
    merek: 'D-Light / Worldscreen 70x70 Inch',
    spesifikasi: 'Ukuran 178x178 cm Portable Stand Tripod',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Kelas Belajar (20 Kelas)',
    jumlah: 20,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 500000,
    serialNumber: 'SCR-2023-001/020',
    kodeBarangBmd: '02.06.01.05.002',
    nomorRegisterBmd: '000011',
    nomorRegister: '000011',
    catatan: 'Pengadaan Layar Proyektor Kelas Tahap 1 & 2 (No. Urut RKAS 91 - Rekening 5.2.05.01.02.0001)'
  },
  {
    id: 'SAR-2023-0012',
    nama: 'Printer Epson / Canon All-in-One Ink Tank',
    merek: 'Epson L3210 / Canon G2010',
    spesifikasi: 'Print, Scan, Copy EcoTank Ink Tank System',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha & Guru',
    jumlah: 3,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 3000000,
    serialNumber: 'PRN-2023-001/003',
    kodeBarangBmd: '02.06.01.01.001',
    nomorRegisterBmd: '000012',
    nomorRegister: '000012',
    catatan: 'Pengadaan Printer Tata Usaha & Ujian Tahap 1 & 2 (No. Urut RKAS 93 - Rekening 5.2.02.06.01.0004)'
  },
  {
    id: 'SAR-2023-0013',
    nama: 'Laptop / Komputer Jinjing Pembelajaran',
    merek: 'Acer / Asus / Lenovo Core i3/i5 SSD',
    spesifikasi: 'RAM 8GB, SSD 512GB, Windows 11 Original',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha / Kurikulum',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 10000000,
    serialNumber: 'LPT-2023-001',
    kodeBarangBmd: '02.06.01.04.001',
    nomorRegisterBmd: '000013',
    nomorRegister: '000013',
    catatan: 'Pengadaan Laptop Operasional Sekolah Tahap 1 (No. Urut RKAS 95 - Rekening 5.2.02.10.01.0001)'
  },

  // --- KIB E: BUKU TEKS PELAJARAN UTAMA KURIKULUM MERDEKA KELAS X (RKAS 2023) ---
  {
    id: 'SAR-2023-0014',
    nama: 'Buku Teks Kurikulum Merdeka - Matematika Kelas X SMA/SMK',
    judulBuku: 'Matematika untuk SMA/SMK Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 35400,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000014',
    nomorRegister: '000014',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 26 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0015',
    nama: 'Buku Teks Kurikulum Merdeka - Bahasa Inggris Kelas X SMA',
    judulBuku: 'Bahasa Inggris untuk SMA Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 26100,
    kodeBarangBmd: '05.17.01.01.002',
    nomorRegisterBmd: '000015',
    nomorRegister: '000015',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 27 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0016',
    nama: 'Buku Teks Kurikulum Merdeka - PPKn Kelas X SMA/SMK',
    judulBuku: 'Pendidikan Pancasila dan Kewarganegaraan untuk SMA/SMK Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 28200,
    kodeBarangBmd: '05.17.01.01.003',
    nomorRegisterBmd: '000016',
    nomorRegister: '000016',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 28 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0017',
    nama: 'Buku Teks Kurikulum Merdeka - Bahasa Indonesia Kelas X SMA',
    judulBuku: 'Bahasa Indonesia Kelas 10',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 31200,
    kodeBarangBmd: '05.17.01.01.004',
    nomorRegisterBmd: '000017',
    nomorRegister: '000017',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 29 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0018',
    nama: 'Buku Teks Kurikulum Merdeka - Sejarah Kelas X SMA/MA',
    judulBuku: 'Sejarah untuk SMA/MA Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 35,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 111000,
    kodeBarangBmd: '05.17.01.01.005',
    nomorRegisterBmd: '000018',
    nomorRegister: '000018',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 30 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0019',
    nama: 'Buku Teks Kurikulum Merdeka - PAI & Budi Pekerti Kelas X',
    judulBuku: 'Pendidikan Agama Islam dan Budi Pekerti untuk SMA/SMK Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 42100,
    kodeBarangBmd: '05.17.01.01.006',
    nomorRegisterBmd: '000019',
    nomorRegister: '000019',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 31 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0020',
    nama: 'Buku Teks Kurikulum Merdeka - Informatika Kelas X SMA',
    judulBuku: 'Informatika untuk SMA Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 33600,
    kodeBarangBmd: '05.17.01.01.007',
    nomorRegisterBmd: '000020',
    nomorRegister: '000020',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 32 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0021',
    nama: 'Buku Teks Kurikulum Merdeka - Fisika Kelas X SMA/MA',
    judulBuku: 'Fisika untuk SMA/MA Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 35,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 65000,
    kodeBarangBmd: '05.17.01.01.008',
    nomorRegisterBmd: '000021',
    nomorRegister: '000021',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 33 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0022',
    nama: 'Buku Teks Kurikulum Merdeka - Kimia Kelas X SMA/MA',
    judulBuku: 'Kimia untuk SMA/MA Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 35,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 64000,
    kodeBarangBmd: '05.17.01.01.009',
    nomorRegisterBmd: '000022',
    nomorRegister: '000022',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 34 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0023',
    nama: 'Buku Teks Kurikulum Merdeka - Biologi Kelas X SMA/MA',
    judulBuku: 'Biologi untuk SMA/MA Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 35,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 126000,
    kodeBarangBmd: '05.17.01.01.010',
    nomorRegisterBmd: '000023',
    nomorRegister: '000023',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 35 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0024',
    nama: 'Buku Teks Kurikulum Merdeka - Sosiologi Kelas X SMA/MA',
    judulBuku: 'Sosiologi untuk SMA/MA Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 35,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 88000,
    kodeBarangBmd: '05.17.01.01.011',
    nomorRegisterBmd: '000024',
    nomorRegister: '000024',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 36 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0025',
    nama: 'Buku Teks Kurikulum Merdeka - Geografi Kelas X SMA',
    judulBuku: 'Geografi Kelas X - Buku',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 35,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 130000,
    kodeBarangBmd: '05.17.01.01.012',
    nomorRegisterBmd: '000025',
    nomorRegister: '000025',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 37 - Rekening 5.2.05.01.01.0001)'
  },
  {
    id: 'SAR-2023-0026',
    nama: 'Buku Teks Kurikulum Merdeka - Ekonomi Kelas X SMA/MA',
    judulBuku: 'Ekonomi untuk SMA/MA Kelas X',
    penerbitBuku: 'Kemendikbudristek / Penerbit Resmi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Perpustakaan Sekolah',
    jumlah: 35,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2023,
    hargaPerolehan: 93000,
    kodeBarangBmd: '05.17.01.01.013',
    nomorRegisterBmd: '000026',
    nomorRegister: '000026',
    catatan: 'Pengadaan Buku Kurikulum Merdeka Tahap 2 (No. Urut RKAS 38 - Rekening 5.2.05.01.01.0001)'
  }
];
