import { Aset } from './types';

export const INITIAL_BOSP_2024_ASETS: Aset[] = [
  // --- KIB B: PERALATAN, MESIN, ELEKTRONIK & MEBELER (RKAS 2024) ---
  {
    id: 'SAR-2024-0001',
    nama: 'LCD Proyektor Multimedia',
    merek: 'Epson / InFocus',
    spesifikasi: '3600 Lumens, HDMI/VGA, Resolusi XGA/WXGA',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Media / Pembelajaran',
    jumlah: 2,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 5000000,
    serialNumber: 'PJ-2024-001/002',
    kodeBarangBmd: '02.06.01.05.001',
    nomorRegisterBmd: '000001',
    nomorRegister: '000001',
    catatan: 'Belanja BOSP 2024 Tahap 1 (No. Urut RKAS 196)'
  },
  {
    id: 'SAR-2024-0002',
    nama: 'Layar Overhead / Screen Proyektor Tripod',
    merek: 'D-Light / Worldscreen',
    spesifikasi: 'Ukuran 70x70 inch (178x178 cm), Manual Tripod Stand',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Media / Pembelajaran',
    jumlah: 3,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 500000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.01.05.002',
    nomorRegisterBmd: '000002',
    nomorRegister: '000002',
    catatan: 'Belanja BOSP 2024 Tahap 1 (No. Urut RKAS 197)'
  },
  {
    id: 'SAR-2024-0003',
    nama: 'Printer Canon Pixma G2770 (All-in-One Ink Tank)',
    merek: 'Canon',
    spesifikasi: 'Pixma G2770 Print, Scan, Copy Ink Tank System',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha (TU)',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 2100000,
    serialNumber: 'CN-G2770-2024',
    kodeBarangBmd: '02.06.01.01.001',
    nomorRegisterBmd: '000003',
    nomorRegister: '000003',
    catatan: 'Belanja BOSP 2024 Tahap 2 (No. Urut RKAS 194)'
  },
  {
    id: 'SAR-2024-0004',
    nama: 'Mesin Spesial Optical Effek Printer',
    merek: 'Specialized Printer',
    spesifikasi: 'Optical Effect Imaging & Document Processing Printer',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Tata Usaha (TU)',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 3000000,
    serialNumber: 'OPT-PRN-2024-01',
    kodeBarangBmd: '02.06.01.01.002',
    nomorRegisterBmd: '000004',
    nomorRegister: '000004',
    catatan: 'Belanja BOSP 2024 Tahap 1 (No. Urut RKAS 193)'
  },
  {
    id: 'SAR-2024-0005',
    nama: 'Meja Siswa Standar Sekolah',
    merek: 'Lokal Industri Mebel',
    spesifikasi: 'Rangka Kayu Solid Berkualitas / Besi Pelitur Halus',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Kelas Belajar',
    jumlah: 36,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 350000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.02.01.001',
    nomorRegisterBmd: '000005',
    nomorRegister: '000005',
    catatan: 'Pengadaan Mebeler BOSP 2024 Tahap 2 (No. Urut RKAS 152)'
  },
  {
    id: 'SAR-2024-0006',
    nama: 'Kursi Siswa Standar Sekolah',
    merek: 'Lokal Industri Mebel',
    spesifikasi: 'Rangka Kayu Solid Sandaran Nyaman',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Kelas Belajar',
    jumlah: 36,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 350000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.02.01.002',
    nomorRegisterBmd: '000006',
    nomorRegister: '000006',
    catatan: 'Pengadaan Mebeler BOSP 2024 Tahap 2 (No. Urut RKAS 153)'
  },
  {
    id: 'SAR-2024-0007',
    nama: 'Kamera Pengawas CCTV HD Outdoor/Indoor',
    merek: 'Hikvision / Dahua',
    spesifikasi: 'Resolusi 2MP Full HD, Night Vision IR, Weatherproof',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Lingkungan Sekolah / Koridor',
    jumlah: 4,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 625000,
    serialNumber: 'CCTV-2024-01-04',
    kodeBarangBmd: '02.06.01.05.010',
    nomorRegisterBmd: '000007',
    nomorRegister: '000007',
    catatan: 'Keamanan Lingkungan Sekolah BOSP 2024 (No. Urut RKAS 161)'
  },
  {
    id: 'SAR-2024-0008',
    nama: 'Peralatan Studio Audio / Sound System Sekolah',
    merek: 'Yamaha / Behringer',
    spesifikasi: 'Active Speaker + Mixer Power Audio System',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Guru / Sanggar Seni',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 2000000,
    serialNumber: 'SND-2024-001',
    kodeBarangBmd: '02.06.01.04.001',
    nomorRegisterBmd: '000008',
    nomorRegister: '000008',
    catatan: 'Pengadaan Sarana Audio BOSP 2024 (No. Urut RKAS 160)'
  },
  {
    id: 'SAR-2024-0009',
    nama: 'Microphone Wireless Dual Channel',
    merek: 'Shure / Sennheiser',
    spesifikasi: 'UHF Wireless Mic Dual Receiver + 2 Handheld',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Guru / Upacara',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 2600000,
    serialNumber: 'MIC-WL-2024',
    kodeBarangBmd: '02.06.01.04.002',
    nomorRegisterBmd: '000009',
    nomorRegister: '000009',
    catatan: 'Alat Kantor Lainnya BOSP 2024 (No. Urut RKAS 158)'
  },
  {
    id: 'SAR-2024-0010',
    nama: 'Kipas Angin Dinding / Berdiri Tornado',
    merek: 'Miyako / Regency',
    spesifikasi: 'Ukuran 18-20 Inch Heavy Duty Blade',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang Kelas Belajar',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 1500000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.02.01.005',
    nomorRegisterBmd: '000010',
    nomorRegister: '000010',
    catatan: 'Belanja BOSP 2024 Tahap 1 (No. Urut RKAS 159)'
  },
  {
    id: 'SAR-2024-0011',
    nama: 'Mesin Pemotong Rumput Gendong 4-Tak',
    merek: 'Honda / Tasco',
    spesifikasi: 'Mesin 4-Tak OHV, Hemat Bahan Bakar, Pisau Baja',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Gudang Sarpras',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 3500000,
    serialNumber: 'MTR-4T-2024',
    kodeBarangBmd: '02.06.03.01.001',
    nomorRegisterBmd: '000011',
    nomorRegister: '000011',
    catatan: 'Pemeliharaan Kebersihan Halaman BOSP 2024 (No. Urut RKAS 154)'
  },
  {
    id: 'SAR-2024-0012',
    nama: 'Tandu Lipat Emergency Aluminium (UKS)',
    merek: 'Gea / Onemed',
    spesifikasi: 'Aluminium Alloy Lipat 2 / 4 dengan Sabuk Pengaman',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang UKS',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 3000000,
    serialNumber: 'TND-UKS-2024-01/02',
    kodeBarangBmd: '02.06.04.01.001',
    nomorRegisterBmd: '000012',
    nomorRegister: '000012',
    catatan: 'Penyelenggaraan UKS BOSP 2024 (No. Urut RKAS 50)'
  },
  {
    id: 'SAR-2024-0013',
    nama: 'Matras Busa UKS / Kesehatan',
    merek: 'Olympus / Serenity',
    spesifikasi: 'Busa Density Tinggi Tebal 10-15 cm Cover Anti Air',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang UKS',
    jumlah: 2,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 2200000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.04.01.002',
    nomorRegisterBmd: '000013',
    nomorRegister: '000013',
    catatan: 'Peralatan Tidur Pasien UKS BOSP 2024 (No. Urut RKAS 51)'
  },
  {
    id: 'SAR-2024-0014',
    nama: 'Timbangan Badan Digital Medis (UKS)',
    merek: 'Camry / Gea Medical',
    spesifikasi: 'Kapasitas 180 Kg, Presisi 100gr, Layar LCD Backlight',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Ruang UKS',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 420000,
    serialNumber: 'TMB-DGT-2024',
    kodeBarangBmd: '02.06.04.01.003',
    nomorRegisterBmd: '000014',
    nomorRegister: '000014',
    catatan: 'Peralatan Diagnostik UKS BOSP 2024 (No. Urut RKAS 49)'
  },
  {
    id: 'SAR-2024-0015',
    nama: 'Mesin Pompa Air Otomatis',
    merek: 'Shimizu / Panasonic',
    spesifikasi: 'Daya 125-200 Watt Otomatis Sumur Dangkal / Pendorong',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Sumber Air / Lingkungan',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 600000,
    serialNumber: 'PMP-2024-01',
    kodeBarangBmd: '02.06.03.01.005',
    nomorRegisterBmd: '000015',
    nomorRegister: '000015',
    catatan: 'Instalasi Sanitasi Air Sekolah BOSP 2024 (No. Urut RKAS 186)'
  },
  {
    id: 'SAR-2024-0016',
    nama: 'Kompor Gas Turbo Dapur Sekolah',
    merek: 'Rinnai / Quantum',
    spesifikasi: '2 Tungku Burner Kuningan Komersil',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Dapur / Ruang Guru',
    jumlah: 1,
    satuan: 'Unit',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 600000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.02.01.010',
    nomorRegisterBmd: '000016',
    nomorRegister: '000016',
    catatan: 'Peralatan Rumah Tangga Sekolah BOSP 2024 (No. Urut RKAS 174)'
  },
  {
    id: 'SAR-2024-0017',
    nama: 'Tangki Sprayer Kebun & Disinfektan Manual/Elektrik',
    merek: 'Swan / CBA',
    spesifikasi: 'Kapasitas 16 Liter Nozzle Kuningan',
    kategori: 'KIB B (Peralatan dan Mesin)',
    ruangLokasi: 'Gudang Sarpras',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 600000,
    serialNumber: '-',
    kodeBarangBmd: '02.06.03.01.006',
    nomorRegisterBmd: '000017',
    nomorRegister: '000017',
    catatan: 'Alat Kebersihan & Sanitasi BOSP 2024 (No. Urut RKAS 151)'
  },

  // --- KIB E: ALAT OLAHRAGA TAHAN LAMA (RKAS 2024) ---
  {
    id: 'SAR-2024-0018',
    nama: 'Raket Badminton Carbon Graphite',
    merek: 'Yonex / Lining',
    spesifikasi: 'Frame Carbon Graphite + Senar Tarikan 24-28 lbs',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 1,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 250000,
    kodeBarangBmd: '05.17.02.01.001',
    nomorRegisterBmd: '000018',
    nomorRegister: '000018',
    catatan: 'Peralatan Praktik Olahraga BOSP 2024 (No. Urut RKAS 206)'
  },
  {
    id: 'SAR-2024-0019',
    nama: 'Net Bola Voli Standar PBVSI',
    merek: 'Mikasa / Molten',
    spesifikasi: 'Tali Seling Baja Panjang 9.5 Meter Lebar 1 Meter',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 3,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 250000,
    kodeBarangBmd: '05.17.02.01.002',
    nomorRegisterBmd: '000019',
    nomorRegister: '000019',
    catatan: 'Peralatan Praktik Olahraga BOSP 2024 (No. Urut RKAS 212 & 216)'
  },
  {
    id: 'SAR-2024-0020',
    nama: 'Net Sepak Takraw Standar PSTI',
    merek: 'Gajah Emas / Marathon',
    spesifikasi: 'Bahan Nylon Kuat Standar Pertandingan',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 3,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 95000,
    kodeBarangBmd: '05.17.02.01.003',
    nomorRegisterBmd: '000020',
    nomorRegister: '000020',
    catatan: 'Peralatan Praktik Olahraga BOSP 2024 (No. Urut RKAS 210 & 219)'
  },
  {
    id: 'SAR-2024-0021',
    nama: 'Bola Sepak Bola / Bola Kaki Standar FIFA Size 5',
    merek: 'Mikasa / Molten / Specs',
    spesifikasi: 'Bahan PU Leather Jahit Mesin Presisi',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 8,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 375000,
    kodeBarangBmd: '05.17.02.01.004',
    nomorRegisterBmd: '000021',
    nomorRegister: '000021',
    catatan: 'Peralatan Olahraga BOSP 2024 (No. Urut RKAS 209 & 215)'
  },
  {
    id: 'SAR-2024-0022',
    nama: 'Bola Voli Standar PBVSI',
    merek: 'Mikasa MVA300 / Molten V5M',
    spesifikasi: 'Soft Touch Laminated Polyurethane',
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Alat Olahraga/Peraga',
    ruangLokasi: 'Ruang Olahraga',
    jumlah: 7,
    satuan: 'Buah',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2024,
    hargaPerolehan: 450000,
    kodeBarangBmd: '05.17.02.01.005',
    nomorRegisterBmd: '000022',
    nomorRegister: '000022',
    catatan: 'Peralatan Olahraga BOSP 2024 (No. Urut RKAS 211 & 214)'
  }
];
