import { Aset } from './types';

export const INITIAL_SIPLAH_BUKU_ASETS: Aset[] = [
  // === PEMBELIAN 1: CV. MEDIA RAZAK (INV/SCMR-0022/INVOICE_2506-100719 - 30 Juni 2025) ===
  {
    id: 'ATL-2025-0001',
    nama: 'Buku Teks Siswa: Geografi Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Geografi untuk SMA/MA Kelas XI',
    pengarangBuku: 'Budi Handoyo',
    penerbitBuku: 'Pusat Perbukuan Kemendikbudristek / Media Razak (SIPLah)',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 22,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 121000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000101',
    nomorRegister: '000101',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0002',
    nama: 'Buku Teks Siswa: Sosiologi Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Sosiologi untuk SMA/MA Kelas XI',
    pengarangBuku: 'Joan Hesti Gita Purwasih',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 23,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 115000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000102',
    nomorRegister: '000102',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0003',
    nama: 'Buku Teks Siswa: Ekonomi Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Ekonomi untuk SMA/MA Kelas XI',
    pengarangBuku: 'Yeni Fitriani',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 22,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 112000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000103',
    nomorRegister: '000103',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0004',
    nama: 'Buku Teks Siswa: Sejarah Kelas X SMA',
    judulBuku: 'Sejarah untuk SMA/MA Kelas X',
    pengarangBuku: 'Sari Oktafiana',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 13,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 115000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000104',
    nomorRegister: '000104',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0005',
    nama: 'Buku Teks Siswa: Sosiologi Kelas X SMA (Kurikulum Merdeka)',
    judulBuku: 'Sosiologi untuk SMA/MA Kelas X',
    pengarangBuku: 'Sari Oktafiana',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 13,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 109000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000105',
    nomorRegister: '000105',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0006',
    nama: 'Buku Teks Siswa: Kimia Kelas X SMA (Kurikulum Merdeka)',
    judulBuku: 'Kimia untuk SMA/MA Kelas X',
    pengarangBuku: 'Ayuk Ratna Puspaningsih',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 13,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 124000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000106',
    nomorRegister: '000106',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0007',
    nama: 'Buku Teks Siswa: Geografi Kelas X SMA (Kurikulum Merdeka)',
    judulBuku: 'Geografi untuk SMA/MA Kelas X',
    pengarangBuku: 'Budi Handoyo',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 13,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 121000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000107',
    nomorRegister: '000107',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0008',
    nama: 'Buku Teks Siswa: Sejarah Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Sejarah untuk SMA/MA Kelas XI',
    pengarangBuku: 'Martina Safitry',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 22,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 112000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000108',
    nomorRegister: '000108',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0009',
    nama: 'Buku Teks Siswa: Biologi Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Biologi untuk SMA/MA Kelas XI',
    pengarangBuku: 'Rini Solihat',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 22,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 140000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000109',
    nomorRegister: '000109',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0010',
    nama: 'Buku Siswa: Cerdas Cergas Berbahasa & Bersastra Indonesia Kelas XI',
    judulBuku: 'Cerdas Cergas Berbahasa dan Bersastra Indonesia Kelas XI',
    pengarangBuku: 'Henny Marwati',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 18,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 30000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000110',
    nomorRegister: '000110',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0011',
    nama: 'Buku Teks Siswa: Matematika Kelas XI SMA/SMK',
    judulBuku: 'Matematika untuk SMA/SMK Kelas XI',
    pengarangBuku: 'Dick Susanto',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 27,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 22100,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000111',
    nomorRegister: '000111',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0012',
    nama: 'Buku Teks Siswa: PAI dan Budi Pekerti Kelas XI SMA/SMK',
    judulBuku: 'Pendidikan Agama Islam dan Budi Pekerti Kelas XI',
    pengarangBuku: 'Abd. Rahman',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 29,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 45700,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000112',
    nomorRegister: '000112',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0013',
    nama: 'Buku Teks: Fisika Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Fisika untuk SMA/MA Kelas XI',
    pengarangBuku: 'Marianna Magdalena Radjawane',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 22,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 157000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000113',
    nomorRegister: '000113',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0014',
    nama: 'Buku Teks: Kimia Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Kimia untuk SMA/MA Kelas XI',
    pengarangBuku: 'Munasprianto Ramli',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 23,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 137000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000114',
    nomorRegister: '000114',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0015',
    nama: 'Buku Teks: Informatika Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Informatika untuk SMA Kelas XI',
    pengarangBuku: 'Iryanto',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 30,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 38500,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000115',
    nomorRegister: '000115',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },
  {
    id: 'ATL-2025-0016',
    nama: 'Buku Teks: Bahasa Inggris English for Change Kelas XI',
    judulBuku: 'English for Change SMA/MA Grade XI',
    pengarangBuku: 'Puji Astuti',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 26,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 35900,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000116',
    nomorRegister: '000116',
    catatan: 'Invoice SIPLah: INV/SCMR-0022/INVOICE_2506-100719, LUNAS'
  },

  // === PEMBELIAN 2: CV. MEDIA RAZAK - KELAS XII (Invoice: 250919172614828656 - 25 Nov 2025) ===
  {
    id: 'ATL-2025-0017',
    nama: 'Buku Teks Siswa: Biologi Kelas XII SMA (Kurikulum Merdeka)',
    judulBuku: 'Biologi untuk SMA/MA Kelas XII',
    pengarangBuku: 'Shubhi Mahmashony Harimurti',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 17,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 124000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000117',
    nomorRegister: '000117',
    catatan: 'Invoice SIPLah: 250919172614828656, LUNAS'
  },
  {
    id: 'ATL-2025-0018',
    nama: 'Buku Teks Siswa: Fisika Kelas XII SMA (Kurikulum Merdeka)',
    judulBuku: 'Fisika untuk SMA/MA Kelas XII',
    pengarangBuku: 'Lia Laela Sarah',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 14,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 159000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000118',
    nomorRegister: '000118',
    catatan: 'Invoice SIPLah: 250919172614828656, LUNAS'
  },
  {
    id: 'ATL-2025-0019',
    nama: 'Buku Teks Siswa: Kimia Kelas XII SMA (Kurikulum Merdeka)',
    judulBuku: 'Kimia untuk SMA/MA Kelas XII',
    pengarangBuku: 'Galuh Yuliani',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 17,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 139000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000119',
    nomorRegister: '000119',
    catatan: 'Invoice SIPLah: 250919172614828656, LUNAS'
  },
  {
    id: 'ATL-2025-0020',
    nama: 'Buku Teks Siswa: Sosiologi Kelas XII SMA (Kurikulum Merdeka)',
    judulBuku: 'Sosiologi untuk SMA/MA Kelas XII',
    pengarangBuku: 'Susi Fitri',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 19,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 114000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000120',
    nomorRegister: '000120',
    catatan: 'Invoice SIPLah: 250919172614828656, LUNAS'
  },
  {
    id: 'ATL-2025-0021',
    nama: 'Buku Teks Siswa: Geografi Kelas XII SMA (Kurikulum Merdeka)',
    judulBuku: 'Geografi untuk SMA/MA Kelas XII',
    pengarangBuku: 'Budi Handoyo',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 17,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 127000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000121',
    nomorRegister: '000121',
    catatan: 'Invoice SIPLah: 250919172614828656, LUNAS'
  },
  {
    id: 'ATL-2025-0022',
    nama: 'Buku Teks Siswa: Ekonomi Kelas XII SMA (Kurikulum Merdeka)',
    judulBuku: 'Ekonomi untuk SMA/MA Kelas XII',
    pengarangBuku: 'Aisyah Nurjanah',
    penerbitBuku: 'Kemendikbudristek / SIPLah Blibli',
    tahunCetakBuku: 2024,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 17,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2025,
    hargaPerolehan: 117000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000122',
    nomorRegister: '000122',
    catatan: 'Invoice SIPLah: 250919172614828656, LUNAS'
  },

  // === PEMBELIAN 3: PT. INTAN PARIWARA (INV2026050001095 - 21 Mei 2026) ===
  {
    id: 'ATL-2026-0001',
    nama: 'Buku Teks Siswa: Matematika Kelas X SMA/SMK (Edisi Revisi)',
    judulBuku: 'Matematika untuk SMA/SMK Kelas X (Edisi Revisi)',
    pengarangBuku: 'Dick Susanto',
    penerbitBuku: 'PT. Intan Pariwara (TB Kandai Pustaka, SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 35400,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000201',
    nomorRegister: '000201',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0002',
    nama: 'Buku Teks Siswa: Cerdas Cergas Bahasa Indonesia Kelas XI (Edisi Revisi)',
    judulBuku: 'Cerdas Cergas Berbahasa Indonesia Kelas XI (Edisi Revisi)',
    pengarangBuku: 'Henny Marwati',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 43600,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000202',
    nomorRegister: '000202',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0003',
    nama: 'Buku Teks Siswa: Matematika Tingkat Lanjut Kelas XI (Edisi Revisi)',
    judulBuku: 'Matematika Tingkat Lanjut SMA/MA Kelas XI (Edisi Revisi)',
    pengarangBuku: 'Al Azhary Masta',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 43600,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000203',
    nomorRegister: '000203',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0004',
    nama: 'Buku Teks Siswa: Sosiologi Kelas XI SMA (Edisi Revisi)',
    judulBuku: 'Sosiologi untuk SMA/MA Kelas XI (Edisi Revisi)',
    pengarangBuku: 'Joan Hesti Gita Purwasih',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 31400,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000204',
    nomorRegister: '000204',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0005',
    nama: 'Buku Teks Siswa: Geografi Kelas XI SMA (Edisi Revisi)',
    judulBuku: 'Geografi untuk SMA/MA Kelas XI (Edisi Revisi)',
    pengarangBuku: 'Budi Handoyo',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 39500,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000205',
    nomorRegister: '000205',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0006',
    nama: 'Buku Teks Siswa: Ekonomi Kelas XI SMA (Edisi Revisi)',
    judulBuku: 'Ekonomi untuk SMA/MA Kelas XI (Edisi Revisi)',
    pengarangBuku: 'Yeni Fitriani',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 30700,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000206',
    nomorRegister: '000206',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0007',
    nama: 'Buku Teks Siswa: PJOK Kelas X SMA/SMK',
    judulBuku: 'Pendidikan Jasmani, Olahraga, dan Kesehatan Kelas X',
    pengarangBuku: 'Abdul Rauf',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 33400,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000207',
    nomorRegister: '000207',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0008',
    nama: 'Buku Teks Siswa: PJOK Kelas XI SMA/SMK',
    judulBuku: 'Pendidikan Jasmani, Olahraga, dan Kesehatan Kelas XI',
    pengarangBuku: 'Abdul Rauf',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 35500,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000208',
    nomorRegister: '000208',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0009',
    nama: 'Buku Teks Siswa: Ilmu Pengetahuan Alam (IPA) Kelas X',
    judulBuku: 'Ilmu Pengetahuan Alam untuk SMA Kelas X',
    pengarangBuku: 'Ayuk Ratna Puspaningsih',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 34800,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000209',
    nomorRegister: '000209',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0010',
    nama: 'Buku Teks Siswa: Ilmu Pengetahuan Sosial (IPS) Kelas X',
    judulBuku: 'Ilmu Pengetahuan Sosial untuk SMA Kelas X',
    pengarangBuku: 'Sari Oktafiana',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 42100,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000210',
    nomorRegister: '000210',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0011',
    nama: 'Buku Teks Siswa: Informatika Kelas X SMA',
    judulBuku: 'Informatika untuk SMA Kelas X',
    pengarangBuku: 'Mushthofa',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 33600,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000211',
    nomorRegister: '000211',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0012',
    nama: 'Buku Teks Siswa: Bahasa Inggris Work in Progress Kelas X',
    judulBuku: 'Work in Progress SMA/SMK/MA Grade X',
    pengarangBuku: 'Budi Hermawan',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 26100,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000212',
    nomorRegister: '000212',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0013',
    nama: 'Buku Teks Siswa: Biologi Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Biologi untuk SMA/MA Kelas XI',
    pengarangBuku: 'Rini Solihat',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 39000,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000213',
    nomorRegister: '000213',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0014',
    nama: 'Buku Teks Siswa: Kimia Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Kimia untuk SMA/MA Kelas XI',
    pengarangBuku: 'Munasprianto Ramli',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 30400,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000214',
    nomorRegister: '000214',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0015',
    nama: 'Buku Teks Siswa: Fisika Kelas XI SMA (Kurikulum Merdeka)',
    judulBuku: 'Fisika untuk SMA/MA Kelas XI',
    pengarangBuku: 'Marianna Magdalena Radjawane',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 31600,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000215',
    nomorRegister: '000215',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0016',
    nama: 'Buku Teks Siswa: Pendidikan Pancasila Kelas X SMA',
    judulBuku: 'Pendidikan Pancasila untuk SMA/MA/SMK/MAK Kelas X',
    pengarangBuku: 'Rochimudin',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 32200,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000216',
    nomorRegister: '000216',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0017',
    nama: 'Buku Teks Siswa: Pendidikan Pancasila Kelas XI SMA',
    judulBuku: 'Pendidikan Pancasila untuk SMA/MA/SMK/MAK Kelas XI',
    pengarangBuku: 'Rochimudin',
    penerbitBuku: 'PT. Intan Pariwara (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 50,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 26100,
    kodeBarangBmd: '05.17.01.01.001',
    nomorRegisterBmd: '000217',
    nomorRegister: '000217',
    catatan: 'Invoice SIPLah: INV2026050001095, BAST No. BAST2026050001095'
  },
  {
    id: 'ATL-2026-0018',
    nama: 'Kumpulan Paket Buku Panduan Guru Kurikulum Merdeka (Seni, PKWU, PAI, IPA, IPS, Bahasa)',
    judulBuku: 'Buku Panduan Guru Kurikulum Merdeka Terpadu (Fase E & Fase F)',
    pengarangBuku: 'Pusat Perbukuan BSKAP Kemendikbudristek',
    penerbitBuku: 'PT. Intan Pariwara / Media Razak (SIPLah)',
    tahunCetakBuku: 2025,
    kategori: 'KIB E (Aset Tetap Lainnya)',
    jenisAsetLainnya: 'Buku/Perpustakaan',
    ruangLokasi: 'Ruang Perpustakaan',
    jumlah: 45,
    satuan: 'Eksemplar',
    kondisi: 'Baik',
    sumberDana: 'BOS Reguler',
    tahunPerolehan: 2026,
    hargaPerolehan: 145000,
    kodeBarangBmd: '05.17.01.01.002',
    nomorRegisterBmd: '000218',
    nomorRegister: '000218',
    catatan: 'Rekapitulasi Paket Buku Pegangan / Panduan Guru SIPLah 2025/2026'
  }
];
